### ISSUE TITLE
cmi.interaction validation

### ISSUE THREAD

**Issue by brunoilponseisae** [trax-project/trax2-starter-lrs#13]
Hi Sebastien,

I noticed that some statements generated by H5P clients are rejected because the value of object.definition.type is not "http://adlnet.gov/expapi/activities/cmi.interaction"
The xAPI docs says: Interaction Activities SHOULD have the Activity type http://adlnet.gov/expapi/activities/cmi.interaction.

Can we have something like a rule enforcement level that would make SHOULD requirements mandatory or not.

Here is an exemple
```
{"actor":{"objectType":"Agent","name":"guest@example.com","mbox":"mailto:guest@example.com"},"verb":{"id":"http://adlnet.gov/expapi/verbs/answered","display":{"en-US":"answered"}},"object":{"id":"http://localhost/version/9a61e941-a113-4271-8c04-0bedbb10b8db/1","objectType":"Activity","definition":{"extensions":{"http://h5p.org/x-api/h5p-local-content-id":1,"http://h5p.org/x-api/h5p-subContentId":"080661d3-6895-43b1-95ff-7030842d3a1d"},"name":{"en-US":"Aerodynamic center activity 1"},"description":{"en-US":"Choose a null zero-lift moment with : \\(cm_{0}=0\\) and vary the angle of attack and obeserve:\n\nAre the aerodynamic centre F and the point of application of the lift of the wing P1 separated?\n"},"type":"http://id.tincanapi.com/activitytype/resource","interactionType":"choice","correctResponsesPattern":["1"],"choices":[{"id":"1","description":{"en-US":"No\n"}},{"id":"0","description":{"en-US":"Yes\n"}}]}},"context":{"contextActivities":{"parent":[{"id":"http://localhost/version/9a61e941-a113-4271-8c04-0bedbb10b8db","objectType":"Activity","definition":{"type":"http://vocab.xapi.fr/activities/web-content","name":{"en-US":"Aerodynamic center"}}}],"category":[{"id":"http://h5p.org/libraries/H5P.MultiChoice-1.14","objectType":"Activity"}],"grouping":[{"id":"http://localhost","definition":{"type":"http://vocab.xapi.fr/activities/system"}},{"id":"http://localhost/version/9a61e941-a113-4271-8c04-0bedbb10b8db","objectType":"Activity","definition":{"type":"http://vocab.xapi.fr/activities/web-content","name":{"en-US":"Aerodynamic center"}}},{"id":"http://localhost/nugget/5adc10ef-8bb5-4808-a49b-eaf3a8b30fcc"}]},"extensions":{"http://id.tincanapi.com/extension/ending-point":1}},"result":{"score":{"min":0,"max":1,"raw":0,"scaled":0},"completion":true,"success":false,"duration":"PT3209.36S","response":""}} 
```

Sincere regards,
Bruno

**Comment by sfraysse** [comment]
Hi Bruno,

I don't think TRAX LRS rejects the statement because of the activity type.

However, I noticed that the activity description contains a `\\` sequence which is usually reserved to escape characters . It is possible that the JSON parser rejects the statement because of that. Do you have any way to remove the `\\` of the description and to test again?

Sebastien

**Comment by brunoilponseisae** [comment]
Hello,

I am almost sure because I put some error_log statements to track down the issue and when I change
`      'type' => ['format' => 'iri', 'value' => 'http://adlnet.gov/expapi/activities/cmi.interaction'], `
with
`       'type' => ['format' => 'iri' ], `
in
/services/trax/framework/xapi-validation/src/Parsing/StatementSchema.php => $interaction_definition

it works. Maybe I don't have the right version of the code?

Regards,
Bruno

**Comment by sfraysse** [comment]
Hi Bruno,

Not with the example you gave me. Maybe the issue comes from another example?
Could you call me please (I don't find your phone number)?

Sébastien

**Comment by sfraysse** [comment]
Ok, I got it. Let me check the impact in terms of conformance...

**Comment by sfraysse** [comment]
Ok, it does not break the conformance test, so I will make the change.
No additional rule or level for this, it will be the default behavior.

## xAPI best practices

TRAX LRS can be less strict when validating statements as long as it does not affect the xAPI conformance.
However, this is important to remind that the biggest challenge of xAPI is not to record statements coming from many solutions.

**The biggest challenge is to keep data consistent!** In other words, you should check that incoming statements follow best practices, and when it is not the case, you should solve the issue on the data source, or before data is recorded into the LRS.
Otherwise, it may break your capability to make consistent analytics in the future.

**Comment by sfraysse** [comment]
That's done. You can update your beta4 installation.
