### ISSUE TITLE
Commands Cheat Sheet commands

### ISSUE THREAD

**Issue by mxyast** [trax-project/trax2-starter-lrs#33]
Hi,
I followed the TRAX LRS 2.1 - Starter Edition download document completely and ran the site successfully, created an admin and was able to log in.
I am having problems running the commands in the Commands Cheat Sheet. For example, when I run this command 'php artisan statements:seed', I get 'ERROR There are no commands defined in the "statements" namespace.' I get this error. Also, even though I connected to moodle, I cannot receive any statements and no data is created in the database.
I wonder if these two situations are related to each other?
I would be happy if you help.

**Comment by sfraysse** [comment]
Hi,

The reason the `php artisan statements:seed` command is not found is because you are using the Starter Edition, and the console commands you found in the documentation are for the Extended Edition.

Regarding Moodle, it's difficult to help because I don't know what you are using to send xAPI statements from Moodle. But most of time, this is due to a misconfiguration when entering the LRS endpoint (wrong URL).

I hope this will help,

Sébastien

**Comment by mxyast** [comment]
Thank you very much.
I solved the problem.
